# Generated by Django 4.0.2 on 2022-02-25 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0005_rename_city_branch_branch_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current')], default='Saving', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
