# Generated by Django 4.0.2 on 2022-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='MyApp/static/images/'),
        ),
    ]
