# Generated by Django 3.2 on 2022-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0016_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(default=None, upload_to="MyApp/sta"),
        ),
    ]
